### ISSUE TITLE
Duplication in sonar

### ISSUE THREAD

**Issue by alce65** [isdi-coders-2022/Mockify-202210-mad#31]
Hola chicos.
Tenéis en el sonar un aviso de mucha duplicación en un archivo de testing.
Recordad que los test también son código y por tanto se les aplican los mismos principios de diseño, en este caso DRY.
Probablemente podáis solucionarlo subiendo el beforeEach a un describe anterior (más genérico)
Mucho animo con lo que falta

**Comment by luisherreralg** [comment]
Muchísimas gracias por los ánimos y por el feedback de parte de todo el equipo. Ahora mismo nos ponemos manos a la obra con ese archivo de test que da problemas. 
Un saludo y buen domingo!

**Comment by alce65** [comment]
Perfecto.
Cierro el issue.
